version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: task-manager-db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-manager-network

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager-api
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/taskmanager
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - task-manager-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge
